import { MealItem } from "./types";

export const MEAL_ITEMS: MealItem[] = [
  {
    id: "med-harvest-bowl",
    name: "Mediterranean Harvest Bowl",
    description: "A high-end gourmet salad bowl featuring grilled chicken, ripe avocado slices, cherry tomatoes, and quinoa.",
    price: 11.50,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCHZqQYgBuWq3_7fpIMwTNzH6eT6sr9cJfDnCjUzZnyakDjOYXKY1N6E7CNP6MRgXS56QQbh6gfSpfS7STntiwr6hYfkjJedIzRUayn5pUInxvZa8pRqIe_F1wBFTl2LqcDOJolK_KF_7g2fCO8uor9UG9Nvy9ajMQKmdcjv5p0ggUxgeL2Y0MtsqcJZM9zWdN740SopEn-M9upkEFN3sndNc1ZJSQOF8SroMSU0JHM-rXXaZkbKZ4n2O-xX0HSByJkuWLCQmi-0ks",
    rating: 4.8,
    canteen: "Central Canteen",
    category: "Breakfast",
    tags: ["Chef's Choice", "Low Calorie", "High Protein"],
    calories: 410,
    protein: "18g"
  },
  {
    id: "energizing-bowl",
    name: "Energizing Bowl",
    description: "A vibrant health-focused green smoothie bowl topped with sliced banana, blueberries, and chia seeds.",
    price: 9.50,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB9E2sFB6qnCbzlQEJdAMyKJCesWRGQh_l5raXuAAuORk7i-IxNSTTQBb_ui2ZaFDspx7a6kOsI_s4YZujn78Yd-OfVOpRTV02d7yfel4ivaRhnHj_71JSzjVFsI0FEzBV9YcNI-JGORX_tEavjyEMBQax5Rz_d3J2qt0akmlE3HTlP_xU4OSEh0JtpjtNgR_49GASSCAQyQWPSMNHh5l3qCpKOzDZ09gK_rE0UVeovE02oAdkYDZzRk0rtJ-06HoMOjBOeh3Kznvc",
    rating: 4.6,
    canteen: "Gym Cafe",
    category: "Breakfast",
    tags: ["Veg", "Vegan", "Low Calorie", "Brain Food"],
    calories: 320,
    protein: "8g"
  },
  {
    id: "avocado-toast",
    name: "Avocado Toast",
    description: "Modern avocado toast on sourdough bread with a perfectly poached egg and red pepper flakes.",
    price: 7.80,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCh294gj6vV-4GlBmcTukUkb2bvWh1Z-bZwx9NS94792wXxFRWzW2jrStZ6Dvk0gUj6M4a5LYqNsC0ITnhEc83l6NI-f5C-Q_5o3YYOkZeDXI2P8ugHlq0nSXk3kC88_MiaN9LtoA4AvigPRdmGxUQZwQ_VcHDYQk5mCjdYrsQ5WUmjOzTiGzKC3UbGg6LdOe3LF1yHoGf-_vbtnnxrFlTUUjN0L8bXh3PzR1SuJ9ZMvE7GScSTyTrjChzwPRv__YrXmwyb1yr0mAo",
    rating: 4.7,
    canteen: "Central Cafe",
    category: "Breakfast",
    tags: ["Veg", "Chef's Choice"],
    calories: 380,
    protein: "12g"
  },
  {
    id: "classic-burger",
    name: "Classic Double Burger",
    description: "A gourmet classic cheeseburger with melting cheddar, fresh lettuce, tomato, and seasoned double beef patties.",
    price: 8.50,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBSYF5wTQXPv73lOnBTSg6qxpqYnPE5UrdOCTiSiopaoGTSBsfpILZhxrm14ySkivCkwDUjSY5DridIP8F7orH-qu7cIwzps8egqZfs3YT5xq1watGAbPkuXWfXzMMO8fupo-Eb2knMaSE0EQGeGU2bD-A9gacqPH7j8Te2XssPxonwFnrPLHGyIrxXe591SKPJ9x-sZStCWrh1FjoN0aZ3gljgGRnlvG0GzY7qM1uvx45BCiO0AFcHxhbe5I-3q9elZSSH1n2U9ko",
    rating: 4.8,
    canteen: "North Canteen",
    category: "Meals",
    tags: ["Best Seller", "High Protein"],
    calories: 680,
    protein: "36g"
  },
  {
    id: "quinoa-power-bowl",
    name: "Quinoa Power Bowl",
    description: "Roasted chicken, black beans, quinoa, shredded carrots, chickpeas, fresh greens, and spicy lime dressing.",
    price: 12.50,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB5TaQMBHYx3Q6cUZ9WP-9H75wTycmvkwTdYG3cQzW3Q3f6bfdvJc17fSiifkRUmWYklq0W9DPUIbXvA8RoYT7Wk5uRkn7zekdrhroeP3xbvyRJBifusmow729ZGpgT87rfbuomNIeJQUPTezrN3ytnpY5ZREatxoVNsuX9_7VSezl7sTgIlYfUQNEgZdO020t9696La3RFxCxf0db5yks5V53-FUujeM__6bSssfq6fH7bOvXAWy5TyUQw1m3I1BEJpDb938gGMpg",
    rating: 4.8,
    canteen: "Engineering Canteen",
    category: "Meals",
    tags: ["High Protein", "Veg"],
    calories: 420,
    protein: "24g"
  },
  {
    id: "med-zest-platter",
    name: "Mediterranean Zest Platter",
    description: "A balanced mix of plant-based proteins, heart-healthy fats, and complex carbs. Perfect for long study sessions.",
    price: 14.00,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuA3sr0-j_HKi064YJ4O4Z4Ihv27S8-OhFiyWNo2G84PgJK3QPSoMLFahOATKMfO3kvWcD8zgkSCF_AF-Jgm-M5z3S0oWq96vuJXn1BboLqaMBgnxImB5QqXzkVrsnJtjAXhOxvAY9xZVboO_hbWyttJ-NvHw0rNX6p2dmVBy3ehdxHRWcP5SiwuKnmXxWbfCbkM9rufDnUbf3Qk8GWQENhtipxsgIY_QOa49GxsHN11mbrTId4A7yHSoXg46zqLan85cNUrNGfNNy0",
    rating: 4.9,
    canteen: "Central Canteen",
    category: "Meals",
    tags: ["Chef's Choice", "Daily Special"],
    calories: 540,
    protein: "24g"
  },
  {
    id: "salmon-rolls",
    name: "Salmon Zen Rolls",
    description: "Fresh Atlantic salmon with avocado, cucumber, and seaweed, served with pickled ginger on a clean dark plate.",
    price: 15.75,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBG7VLh4cSfz5lfNuFUzU8VYuNdsTYlEh-n26MlXt7sjGKCu1-A7l-jTRGeOzWX3VUIc9O9CDrmRy1NzZG-vmi6-e8WumnjMgZgNw4LBZvp-eH8veZTcpnu3nAiHhar1f2OGBBIoKNtraKsaTCpH3R4levnTpPC33gCd7MvMnIGT2ZtaqHkywra7ZEalpf-hmtLVx0QDH1RvIYVqSSk2J0yAqL_2ekKju7t6YzPNldEHZt-gPqHOo9UEgAuvLMKqxMcK_QgWB5SmC4",
    rating: 4.9,
    canteen: "North Canteen",
    category: "Meals",
    tags: ["Low Calorie", "Brain Food"],
    calories: 390,
    protein: "22g"
  },
  {
    id: "berry-omega-bowl",
    name: "Berry Omega Bowl",
    description: "Mixed berries, walnuts, almond granola, strawberries, blueberries, and probiotic Greek yogurt for cognitive support.",
    price: 8.25,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAgZaADdZKf4YAlcSUTYY7bXyoJ-LgB2yJJyTq_HiWK_z-9PyDzXfgU0uOJNRyiZ-kch_wjdItfX43YyEFbKvyVa44NU81Mg9sebcAREpGrAX0un_DCehXT4WCdfj7L54T0-xfZXrs_BqggJ9ishR6IX0aD-tKSon-gbXzmvZBnoiAr7lNW4M0qXATzEH8LbYQoOIIFvt5DL-MEXTAXqnQogAv_lPSdKm2iWYXcFrUeug4NwXgQVK_xQjJNfTb7UN3sKN6kweXYb68",
    rating: 4.7,
    canteen: "Library Cafe",
    category: "Snacks",
    tags: ["Veg", "Low Calorie", "Brain Food"],
    calories: 280,
    protein: "10g"
  },
  {
    id: "oat-latte",
    name: "Oat Latte",
    description: "Creamy espresso latte brewed with organic barista-blend oat milk.",
    price: 4.20,
    image: "", // We can use Icon representation
    rating: 4.5,
    canteen: "Central Cafe",
    category: "Drinks",
    tags: ["Vegan", "Veg"],
    calories: 120,
    protein: "2g"
  },
  {
    id: "acai-cup",
    name: "Acai Cup",
    description: "Blended organic acai berry sorbet served with granola and sliced banana.",
    price: 6.50,
    image: "",
    rating: 4.6,
    canteen: "Central Cafe",
    category: "Snacks",
    tags: ["Veg", "Vegan", "Low Calorie"],
    calories: 210,
    protein: "3g"
  },
  {
    id: "croissant",
    name: "Croissant",
    description: "Flaky, buttery French puff pastry, freshly baked.",
    price: 3.00,
    image: "",
    rating: 4.4,
    canteen: "Central Cafe",
    category: "Snacks",
    tags: ["Veg"],
    calories: 260,
    protein: "5g"
  },
  {
    id: "kombucha-green",
    name: "Kombucha Green",
    description: "Chilled organic green tea kombucha with probiotic flora.",
    price: 4.90,
    image: "",
    rating: 4.6,
    canteen: "Library Cafe",
    category: "Drinks",
    tags: ["Veg", "Vegan", "Low Calorie"],
    calories: 45,
    protein: "0g"
  }
];
